### ISSUE TITLE
Problemas en heroku

### ISSUE THREAD

**Issue by defvol** [mxabierto/consulta#25]
Al momento de hacer deploy:

``` bash
2015-11-17T22:08:11.361019+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/
activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': /app/ap
p/controllers/concerns/commentable_actions.rb:63: syntax error, unexpected ':', 
expecting keyword_end (SyntaxError)
2015-11-17T22:08:11.361029+00:00 app[web.1]: ....to_sym, "#{resource_name}_id": 
resource.id
2015-11-17T22:08:11.361031+00:00 app[web.1]: ...                               ^
2015-11-17T22:08:11.361031+00:00 app[web.1]: /app/app/controllers/concerns/comme
ntable_actions.rb:67: syntax error, unexpected ':', expecting ')'
2015-11-17T22:08:11.361032+00:00 app[web.1]: ...esource_name.pluralize}_count": 
:desc, name: :asc).limit(20)
2015-11-17T22:08:11.361033+00:00 app[web.1]: ...                               ^
2015-11-17T22:08:11.361036+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0
.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in 
require'
```

**Comment by defvol** [comment]
parece de versión de ruby,

voy a fijarla en el Gemfile

**Comment by defvol** [comment]
Resuelto en #28
